luci-app-n2n_v2: upgrade to v3
immortalwrt/luci pull request #198
Opened 2022-06-24 20:16 UTC by hecheng337

1. 整个包从 **luci-app-n2n_v2** 重命名为 **luci-app-n2n_v3**
2. 从 lean 仓库拉取了部分更新
3. 减少了子网掩码的选项，直接写16个也太憨了(
4. 将IP动态伪装改为可选项，因为不是每个人都用得到（比如我

![image](https://user-images.githubusercontent.com/57560866/175659684-25430c0d-3a6f-479c-a254-8713c5e1e7be.png)

测试了两天，各项功能在 master 和 18.06 分支上都没有出现问题

另外，因为 ucitrack 在 master 上不可用，“保存与应用” 按钮产生的配置文件更新可能不会拉起 n2n 重启。
在 /usr/lib/lua/luci/model/cbi/n2n_v3.lua 中添加额外的触发器可以修复这个问题

```
function m.commit_handler(self)
    if self.changed then
        os.execute("sh -c 'sleep 3 && /etc/init.d/n2n_v3 restart' &")
    end
end
```

2022-06-25 01:34 UTC, zxlhhyccc commented
建议直接使用大屌的修改，大屌的“保存与应用” 按钮产生的配置文件更新能拉起 n2n 重启

2022-06-25 02:28 UTC, 1715173329 commented
@zxlhhyccc 改为 procd 进程守护即可。

2022-06-25 03:52 UTC, zxlhhyccc commented
> @zxlhhyccc 改为 procd 进程守护即可。

不会啊。。。

2022-06-25 04:45 UTC, 1715173329 requested changes

2022-06-25 04:45 UTC, 1715173329 commented on applications/luci-app-n2n_v3/luasrc/controller/n2n_v3.lua
> -N2N V2 Luci configuration page.Made by 981213
不太明白为何此处要移除掉作者信息。

2022-06-25 04:45 UTC, 1715173329 commented on applications/luci-app-n2n_v3/luasrc/model/cbi/n2n_v3.lua
>  function get_mask(v)
只有下面的 prefix 在引用这个 func，感觉没必要独立出来，直接把数据加到对应位置就好了。
可以把 `ListValue` 改成 `Value`，这样可以允许用户自定义 mask。

2022-06-25 04:45 UTC, 1715173329 commented on applications/luci-app-n2n_v3/luasrc/model/cbi/n2n_v3.lua
> +masquerade.title = translate("Enable IP masquerade")
```suggestion
masquerade = s:option(Flag, "masquerade", translate("Enable IP masquerade"))
```

2022-06-25 09:13 UTC, hecheng337 commented on applications/luci-app-n2n_v3/luasrc/controller/n2n_v3.lua
> -N2N V2 Luci configuration page.Made by 981213
是这样的，我当时看到另外一个文件 applications/luci-app-n2n_v2/luasrc/model/cbi/n2n_v2.lua
文件头部的署名格式和这里不一样，看着难受，手痒就整理了一下
然后这个作者消息一串数字好像找不到是谁（刚刚试着搜了一下，发现其实是能找到的 orz）
看着难受就顺手删掉了

2022-06-25 09:14 UTC, hecheng337 commented on applications/luci-app-n2n_v3/luasrc/model/cbi/n2n_v3.lua
>  function get_mask(v)
明白

2022-06-25 09:22 UTC, hecheng337 commented on applications/luci-app-n2n_v3/luasrc/model/cbi/n2n_v3.lua
>  function get_mask(v)
不对，它这里是因为 edge 和 supernode 都有这个设置，所以放在了一起。感觉这样写是没问题的

2022-06-25 09:27 UTC, hecheng337 commented
> 建议直接使用大屌的修改，大屌的“保存与应用” 按钮产生的配置文件更新能拉起 n2n 重启

这边的实现和 lean 基本是一致的，出问题的原因是 master 分支去掉了 ucitrack 的支持（一个自动检查配置文件更新然后重启应用的机制）在其他版本比如 18.06 上保存与按钮还是正常工作的

2022-06-27 05:10 UTC, 1715173329 commented on applications/luci-app-n2n_v3/luasrc/model/cbi/n2n_v3.lua
>  function get_mask(v)
原来如此，抱歉看走眼了。不过依旧建议把 `ListValue` 改为 `Value`

2022-06-28 17:05 UTC, hecheng337 commented
> ![image](https://user-images.githubusercontent.com/45259624/176228523-8899b5dd-8982-4732-84cd-21ca04a3e28b.png) ![image](https://user-images.githubusercontent.com/45259624/176228969-6d830c49-4041-486a-a9f0-57b1a7af182e.png)

天灵上次加入额外的更改之后我一直在赶作业，还没时间仔细测试 ...
1. 大佬可以等我测试完，代码合并之后再来测试；
2. 可以试试我初始提交的版本。

2022-06-29 22:44 UTC, hecheng337 commented
luci-app-n2n 这边追加的 commit 没有问题，几项功能测试正常

2022-06-29 22:49 UTC, merged

2022-06-30 04:22 UTC, zxlhhyccc commented
> luci-app-n2n 这边追加的 commit 没有问题，几项功能测试正常

哪里修复了上面截图的报错啊？