sync changes in LuCI to match Release 37.2
immortalwrt/luci pull request #208
Opened 2022-08-28 14:58 UTC by xlighting2017

Refer to this [commit](https://github.com/pymumu/smartdns/commit/64e5b326cc53df1fec680cfa28ceec5d8a36fcbc)

2022-08-28 16:09 UTC, 1715173329 requested changes

2022-08-28 16:09 UTC, 1715173329 commented on applications/luci-app-smartdns/htdocs/luci-static/resources/view/smartdns/smartdns.js
> +return L.view.extend({
Please keep this as-is.

2022-08-28 16:09 UTC, 1715173329 commented on applications/luci-app-smartdns/htdocs/luci-static/resources/view/smartdns/smartdns.js
> -'require view';
Please keep this as-is.

2022-08-29 01:56 UTC, xlighting2017 commented
changed based on review comments

2022-08-29 02:25 UTC, 1715173329 approved these changes

2022-08-29 02:27 UTC, merged