luci-app-smartdns: bump to 1.2023.41
immortalwrt/luci pull request #286
Opened 2023-03-18 14:18 UTC by SakuraFallingMad

2023-03-18 14:52 UTC, 1715173329 requested changes

2023-03-18 14:52 UTC, 1715173329 commented on applications/luci-app-smartdns/Makefile
> +PKG_RELEASE:=1
```suggestion
```

2023-03-18 14:52 UTC, 1715173329 commented on applications/luci-app-smartdns/Makefile
> +
```suggestion
```

2023-03-18 14:52 UTC, 1715173329 commented on applications/luci-app-smartdns/po/zh_Hans/smartdns.po
> +msgstr "额外的服务器参数"
翻译错误？

2023-03-18 14:52 UTC, 1715173329 commented on applications/luci-app-smartdns/root/usr/share/luci/menu.d/luci-app-smartdns.json
> -			"acl": [ "luci-app-smartdns" ],
保持原样

2023-03-18 23:53 UTC, SakuraFallingMad commented on applications/luci-app-smartdns/po/zh_Hans/smartdns.po
> +msgstr "额外的服务器参数"
搬运[pymumu](https://github.com/pymumu)的，将错就错？

2023-03-19 02:57 UTC, 1715173329 commented on applications/luci-app-smartdns/po/zh_Hans/smartdns.po
> +msgstr "额外的服务器参数"
可以考虑给上游提个 PR 修一下

2023-03-19 02:57 UTC, 1715173329 approved these changes
lgtm - thanks!

2023-03-19 02:58 UTC, merged